name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs: 
  build: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install NodeJS
      uses: action/setup-node@v2-beta
      with:
        node-version: 12
    - uses: borales/actions-yarn@v2.0.0
      with:
        cmd: install
    - name: Build React App
      run: npm install --global surge
    - name: Deploy to Surge
      run: surge ./build react-expense-tracker-sarmad.surge.sh --token ${{secrets.EXPENSE_TRACKER_SECRET}}
      
     
  
    
